import type { Metadata } from "next";
import localFont from "next/font/local";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v14-appRouter";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import HeaderNav from "@/components/header-nav";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
import logout from "@/actions/logout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = authenticated();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
       <AppRouterCacheProvider>
          <Providers authenticated={isAuthenticated}>
            <CssBaseline />
            <HeaderNav logout={logout} />
            <Container>{children}</Container>
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
